# Generated by Django 5.2.6 on 2025-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp', models.TextField(blank=True, null=True)),
                ('ice_candidates', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, editable=False, max_length=64)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
