# Generated by Django 5.2.6 on 2025-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(max_length=45)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('contact_no', models.CharField(max_length=45, unique=True)),
            ],
        ),
    ]
