# Generated by Django 5.2.6 on 2025-11-27 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(max_length=45)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('contact_no', models.CharField(max_length=45, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pharmacy_id', 'user')},
            },
        ),
    ]
