# Generated by Django 5.2.6 on 2025-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ice_candidates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sdp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
