# Generated by Django 5.2.6 on 2025-11-27 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientRecord', '0001_initial'),
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInstance',
            fields=[
                ('instance_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('patient_medicine_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('days_of_intake', models.CharField(blank=True, max_length=45, null=True)),
                ('intake_note', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientRecord.patientrecord')),
            ],
        ),
    ]
