# Generated by Django 5.2.6 on 2025-09-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicine', '0001_initial'),
        ('PatientRecord', '0001_initial'),
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinstance',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine'),
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='patient_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientRecord.patientrecord'),
        ),
    ]
