# Generated by Django 5.2.6 on 2025-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=45, unique=True)),
                ('hospital_name', models.CharField(max_length=45)),
                ('bio', models.TextField()),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=45)),
            ],
        ),
    ]
